# Fields
# name           -> Product name (str)
# type           -> Set to 'product' (str)
# volume         -> Number of slots taken (int)
# marginal_costs -> Profit made on item at each breakpoint (list of float)
# breakpoints    -> The upper limits of the marginal costs
# demand         -> Expected demand for item (float)
# penalty        -> Short supply penalty (float)
# interactions   -> Interactions with other products (list of interact dicts)
# interact       -> Contains information about product interactions
#   name -> Name of other product interaction happens with
#   val  -> Interaction value

x01: {
  name: Gloves (Small),
  type: product,
  volume: 1,
  marginal_costs: [8.75],
  breakpoints: [],
  demand: 4,
  interactions: [
    {
      name: Gloves (Medium),
      val: -0.1
    },
    {
      name: Gloves (Large),
      val: -0.1
    }
  ],
  penalty: 0
}
x02: {
  name: Gloves (Medium),
  type: product,
  volume: 1,
  marginal_costs: [8.75],
  breakpoints: [],
  demand: 6,
  interactions: [
    {
      name: Gloves (Large),
      val: -0.1
    }
  ],
  penalty: 0
}
x03: {
  name: Gloves (Large),
  type: product,
  volume: 1,
  marginal_costs: [8.75],
  breakpoints: [],
  demand: 5,
  interactions: [],
  penalty: 0
}
x04: {
  name: Fabric Mask (Adult),
  type: product,
  volume: 1,
  marginal_costs: [40],
  breakpoints: [],
  demand: 3,
  interactions: [
    {
      name: Fabric Mask (Kids),
      val: -0.05
    },
    {
      name: Disposable Mask,
      val: -0.1
    }
    ],
  penalty: 0
}
x05: {
  name: Fabric Mask (Kids),
  type: product,
  volume: 1,
  marginal_costs: [20],
  breakpoints: [],
  demand: 0.5,
  interactions: [
   {
      name: Disposable Mask,
      val: -0.1
    }],
  penalty: 0
}
x06: {
  name: Disposable Mask,
  type: product,
  volume: 1,
  marginal_costs: [2],
  breakpoints: [],
  demand: 20,
  interactions: [
  {
      name: Ear Saver,
      val: 0.2
    }],
  penalty: 50
}
x07: {
  name: Hand Sanitizer (Scented),
  type: product,
  volume: 1,
  marginal_costs: [10],
  breakpoints: [],
  demand: 1,
  interactions: [
  {
      name: Hand Sanitizer (Unscented),
      val: -0.1
    }],
  penalty: 0
}
x08: {
  name: Hand Sanitizer (Unscented),
  type: product,
  volume: 1,
  marginal_costs: [10],
  breakpoints: [],
  demand: 1,
  interactions: [],
  penalty: 0
}
x09: {
  name: Face Shield,
  type: product,
  volume: 2,
  marginal_costs: [30],
  breakpoints: [],
  demand: 1,
  interactions: [],
  penalty: 0
}
x10: {
  name: Ear Saver,
  type: product,
  volume: 1,
  marginal_costs: [5],
  breakpoints: [],
  demand: 1,
  interactions: [],
  penalty: 0
}
x11: {
  name: Lysol Wipes,
  type: product,
  volume: 1,
  marginal_costs: [10],
  breakpoints: [],
  demand: 10,
  interactions: [],
  penalty: 0
}
x12: {
  name: Rubbing Alcohol (250 mL),
  type: product,
  volume: 1,
  marginal_costs: [7],
  breakpoints: [],
  demand: 0.5,
  interactions: [],
  penalty: 0
}
x13: {
  name: Door Opener Keychain,
  type: product,
  volume: 1,
  marginal_costs: [15],
  breakpoints: [],
  demand: 0.5,
  interactions: [],
  penalty: 0
}
x14: {
  name: Anti-Fog Wipes,
  type: product,
  volume: 1,
  marginal_costs: [8],
  breakpoints: [],
  demand: 20,
  interactions: [],
  penalty: 0
}
